### ISSUE TITLE
Undefined index: report

### ISSUE THREAD

**Issue by ujovlado** [keboola/sklik-extractor#18]
`docker-e94bb658fac69e5b4534e1d56a8fe362`

```
[2018-09-23 04:05:11] CRITICAL: ErrorException:Undefined index: report {\"errFile\":\"\/code\/src\/SklikApi.php\",\"errLine\":168,\"errCode\":0,\"errTrace\":\"#
0 \/code\/src\/SklikApi.php(168): Keboola\\\\Component\\\\BaseComponent::Keboola\\\\Component\\\\{closure}(8, 'Undefined index...', '\/code\/src\/Sklik...', 168, Array)\
#1 \/code\/src\/Extractor.php(79): Keboola\\\\SklikExtractor\\\\SklikApi->readReport('keywords', '******)...', Array, 14800, 100)\
#2 \/code\/src\/Component.php(26): Keboola\\\\SklikExtractor\\\\Extractor->run(Object(Keboola\\\\SklikExtractor\\\\Config))\
#3 \/code\/src\/run.php(14): Keboola\\\\SklikExtractor\\\\Component->run()\
#4 {main}\",\"errPrevious\":\"\"} []
```

**Comment by JakubMatejka** [comment]
viz. https://github.com/keboola/sklik-extractor/pull/19
